// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj9OkvcKT_vfa1CstHJIGkT8y4KEBsnBE',
    appId: '1:1051848476626:web:03054aa9e4396b1eb02a0b',
    messagingSenderId: '1051848476626',
    projectId: 'snap-theme-b3',
    authDomain: 'snap-theme-b3.firebaseapp.com',
    storageBucket: 'snap-theme-b3.firebasestorage.app',
    measurementId: 'G-1BBJT10H5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZn8zeg0xfQLd4DxE7uOQSAahOhFseFTA',
    appId: '1:1051848476626:android:ec9ec79f326fb292b02a0b',
    messagingSenderId: '1051848476626',
    projectId: 'snap-theme-b3',
    storageBucket: 'snap-theme-b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsgDG8Ai8whUAHAzqMIe1CuyVD7cpzbs0',
    appId: '1:1051848476626:ios:d4cc5216d299a3d3b02a0b',
    messagingSenderId: '1051848476626',
    projectId: 'snap-theme-b3',
    storageBucket: 'snap-theme-b3.firebasestorage.app',
    iosBundleId: 'com.example.snapTheme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsgDG8Ai8whUAHAzqMIe1CuyVD7cpzbs0',
    appId: '1:1051848476626:ios:d4cc5216d299a3d3b02a0b',
    messagingSenderId: '1051848476626',
    projectId: 'snap-theme-b3',
    storageBucket: 'snap-theme-b3.firebasestorage.app',
    iosBundleId: 'com.example.snapTheme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj9OkvcKT_vfa1CstHJIGkT8y4KEBsnBE',
    appId: '1:1051848476626:web:5d0307d8501316fab02a0b',
    messagingSenderId: '1051848476626',
    projectId: 'snap-theme-b3',
    authDomain: 'snap-theme-b3.firebaseapp.com',
    storageBucket: 'snap-theme-b3.firebasestorage.app',
    measurementId: 'G-B9YH829XX8',
  );
}
